"""initial_ringguard_schema

Revision ID: b1a3f5108e62
Revises: 
Create Date: 2026-09-03 01:07:23.281676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1a3f5108e62'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiaries',
    sa.Column('beneficiary_id', sa.String(length=32), nullable=False),
    sa.Column('beneficiary_type', sa.String(length=64), nullable=False),
    sa.Column('bank_ifsc_prefix', sa.String(length=16), nullable=False),
    sa.Column('account_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('beneficiary_id', name=op.f('pk_beneficiaries'))
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('customer_name', sa.String(length=128), nullable=False),
    sa.Column('customer_email', sa.String(length=128), nullable=False),
    sa.Column('customer_phone_hash', sa.String(length=64), nullable=False),
    sa.Column('risk_tier', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('pk_customers'))
    )
    op.create_table('dataset_metadata',
    sa.Column('metadata_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_name', sa.String(length=64), nullable=False),
    sa.Column('dataset_version', sa.String(length=32), nullable=False),
    sa.Column('generator_version', sa.String(length=32), nullable=False),
    sa.Column('random_seed', sa.BigInteger(), nullable=False),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entity_counts_json', sa.Text(), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('metadata_id', name=op.f('pk_dataset_metadata'))
    )
    op.create_table('devices',
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('device_type', sa.String(length=64), nullable=False),
    sa.Column('device_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_os', sa.String(length=64), nullable=False),
    sa.Column('fingerprint_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('device_id', name=op.f('pk_devices'))
    )
    op.create_table('ips',
    sa.Column('ip_id', sa.String(length=32), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('ip_type', sa.String(length=32), nullable=False),
    sa.Column('asn_org', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('ip_id', name=op.f('pk_ips'))
    )
    op.create_table('merchants',
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('merchant_category', sa.String(length=64), nullable=False),
    sa.Column('merchant_name', sa.String(length=128), nullable=False),
    sa.Column('merchant_risk_rating', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('merchant_id', name=op.f('pk_merchants'))
    )
    op.create_table('accounts',
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('account_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('account_status', sa.String(length=32), nullable=False),
    sa.Column('account_type', sa.String(length=32), nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('scenario_type', sa.String(length=64), nullable=False),
    sa.Column('ground_truth_label', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_accounts_customer_id_customers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', name=op.f('pk_accounts'))
    )
    op.create_index(op.f('ix_accounts_customer_id'), 'accounts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_accounts_ground_truth_label'), 'accounts', ['ground_truth_label'], unique=False)
    op.create_index('ix_accounts_scenario_ground_truth', 'accounts', ['scenario_type', 'ground_truth_label'], unique=False)
    op.create_index(op.f('ix_accounts_scenario_id'), 'accounts', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_accounts_scenario_type'), 'accounts', ['scenario_type'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('beneficiary_id', sa.String(length=32), nullable=True),
    sa.Column('merchant_id', sa.String(length=32), nullable=True),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('ip_id', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('transaction_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('scenario_type', sa.String(length=64), nullable=False),
    sa.Column('ground_truth_label', sa.String(length=32), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_transactions_chk_positive_transaction_amount')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], name=op.f('fk_transactions_account_id_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.beneficiary_id'], name=op.f('fk_transactions_beneficiary_id_beneficiaries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], name=op.f('fk_transactions_device_id_devices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ip_id'], ['ips.ip_id'], name=op.f('fk_transactions_ip_id_ips'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], name=op.f('fk_transactions_merchant_id_merchants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('transaction_id', name=op.f('pk_transactions'))
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index('ix_transactions_account_timestamp', 'transactions', ['account_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_transactions_beneficiary_id'), 'transactions', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_transactions_device_id'), 'transactions', ['device_id'], unique=False)
    op.create_index('ix_transactions_device_timestamp', 'transactions', ['device_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_transactions_ground_truth_label'), 'transactions', ['ground_truth_label'], unique=False)
    op.create_index(op.f('ix_transactions_ip_id'), 'transactions', ['ip_id'], unique=False)
    op.create_index('ix_transactions_ip_timestamp', 'transactions', ['ip_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_transactions_merchant_id'), 'transactions', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_transactions_scenario_id'), 'transactions', ['scenario_id'], unique=False)
    op.create_index('ix_transactions_scenario_label', 'transactions', ['scenario_type', 'ground_truth_label'], unique=False)
    op.create_index(op.f('ix_transactions_scenario_type'), 'transactions', ['scenario_type'], unique=False)
    op.create_index(op.f('ix_transactions_timestamp'), 'transactions', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_timestamp'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_scenario_type'), table_name='transactions')
    op.drop_index('ix_transactions_scenario_label', table_name='transactions')
    op.drop_index(op.f('ix_transactions_scenario_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_merchant_id'), table_name='transactions')
    op.drop_index('ix_transactions_ip_timestamp', table_name='transactions')
    op.drop_index(op.f('ix_transactions_ip_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_ground_truth_label'), table_name='transactions')
    op.drop_index('ix_transactions_device_timestamp', table_name='transactions')
    op.drop_index(op.f('ix_transactions_device_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_beneficiary_id'), table_name='transactions')
    op.drop_index('ix_transactions_account_timestamp', table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_accounts_scenario_type'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_scenario_id'), table_name='accounts')
    op.drop_index('ix_accounts_scenario_ground_truth', table_name='accounts')
    op.drop_index(op.f('ix_accounts_ground_truth_label'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_customer_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('merchants')
    op.drop_table('ips')
    op.drop_table('devices')
    op.drop_table('dataset_metadata')
    op.drop_table('customers')
    op.drop_table('beneficiaries')
    # ### end Alembic commands ###
